### ISSUE TITLE
 Problem with the script

### ISSUE THREAD

**Issue by btwentyone** [ESX-Org/es_camera#1]
Hello, when I type /spectate id of a person nothing happens.
I am superadmin 10 in the database but nothing works and no error appears in F8.
I have long searched but I can not find anything that can help me.

"I have the latest version of es_camera"

Thank you in advance for your assistance.

**Comment by ForthtuN** [comment]
Did you find what was wrong? Getting same

**Comment by Megamind42** [comment]
> Did you find what was wrong? Getting same

Did you figure it out yet?

**Comment by JaroSound** [comment]
Not workin....

**Comment by Mariox6** [comment]
You have to write /spectate (an random number) (ID)
